spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ane_user
    url: jdbc:mysql://192.168.2.100:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.235.237
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.235.237
    port: 6379
env:
  test2
girl:
  name: damimi
  age: 18
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
