spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ane_user
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.235.237
    port: 6379
server:
  port: 8007
